baseURL = "https://danielmartin7.github.io/danielkunz.github.io/"
title = "daniel kunz"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

ignoreErrors = ["error-missing-instagram-accesstoken"]

canonifyURLs = true
relativeURLs = true

[params]
  description = "Your site description"
  copyright = "Copyright © 2023 Daniel Kunz"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = ""
    title = "gallery"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "info"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
